const $ = id => document.getElementById(id);
let catalog, products = [], activeFilter = 'ALL', heroIndex = 0, imageIndex = 0, activeProduct = null, heroTimer;
const money = p => new Intl.NumberFormat('en-US',{style:'currency',currency:p.currency || 'USD'}).format(Number(p.price)||0);
const safeImage = s => typeof s === 'string' && (s.startsWith('data:image/') || /^https?:\/\//.test(s) || /^assets\/[a-zA-Z0-9._/-]+$/.test(s)) ? s : '';
const escapeHTML = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){try{const response=await fetch('catalog.json',{cache:'no-store'});if(!response.ok)throw new Error('Catalog unavailable');catalog=await response.json();products=(catalog.products||[]).filter(p=>p.published!==false);renderFilters();renderProducts();renderHero();startHero();}catch(error){$('productGrid').innerHTML='<p class="empty">CATALOG UNAVAILABLE. PLEASE REFRESH LATER.</p>';console.error(error)}$('year').textContent=new Date().getFullYear();}
function renderFilters(){const tags=[...new Set(products.flatMap(p=>p.tags||[]))].sort();const options=['ALL','NEW',...tags.filter(t=>t.toUpperCase()!=='NEW')];$('filters').replaceChildren(...options.map(tag=>{const b=document.createElement('button');b.className='filter'+(tag===activeFilter?' active':'');b.textContent=tag;b.type='button';b.onclick=()=>{activeFilter=tag;renderFilters();renderProducts()};return b}));}
function renderProducts(){const q=$('search').value.trim().toLowerCase();const matches=products.filter(p=>(activeFilter==='ALL'||(activeFilter==='NEW'?p.isNew:(p.tags||[]).includes(activeFilter)))&&[p.name,p.description,p.collection,...(p.tags||[])].join(' ').toLowerCase().includes(q));$('productCount').textContent=String(products.length).padStart(2,'0');$('emptyState').hidden=matches.length>0;$('productGrid').replaceChildren(...matches.map(p=>{const article=document.createElement('article');article.className='product-card';const first=safeImage(p.images?.[0]);article.innerHTML=`<button class="card-image" type="button" aria-label="View ${escapeHTML(p.name)}"><img src="${escapeHTML(first)}" alt="${escapeHTML(p.name)} T-shirt mockup" loading="lazy">${p.isNew?'<span class="badge">NEW DROP</span>':''}<span class="image-count">${(p.images||[]).length} ${p.images?.length===1?'IMAGE':'IMAGES'}</span></button><div class="card-info"><div class="card-meta">${escapeHTML(p.collection||'NULL//LUX')}</div><h3>${escapeHTML(p.name)}</h3><div class="card-bottom"><strong>${money(p)}</strong><button type="button">EXPLORE ↗</button></div></div>`;article.querySelector('.card-image').onclick=()=>openProduct(p);article.querySelector('.card-bottom button').onclick=()=>openProduct(p);return article}));}
function slides(){const featured=products.filter(p=>p.featured && p.images?.length);return featured.length?featured.flatMap(p=>p.images.map(src=>({src,name:p.name}))):[{src:'assets/editorial.png',name:'Null Lux editorial'}]}
function renderHero(){const entries=slides();heroIndex=(heroIndex+entries.length)%entries.length;const img=$('heroImage'),slide=entries[heroIndex];const set=()=>{img.src=safeImage(slide.src);img.alt=slide.name+' featured mockup';img.classList.remove('fade')};if(catalog?.settings?.carouselStyle==='fade'){img.classList.add('fade');setTimeout(set,180)}else set();$('heroTotal').textContent=String(entries.length).padStart(2,'0');$('heroImage').parentElement.querySelector('.hero-image-label span').textContent=' / '+String(heroIndex+1).padStart(3,'0');}
function startHero(){clearInterval(heroTimer);heroTimer=setInterval(()=>{heroIndex++;renderHero()},Math.max(2,Math.min(20,Number(catalog?.settings?.carouselSeconds)||5))*1000)}
function moveHero(n){heroIndex+=n;renderHero();startHero()}
function openProduct(p){activeProduct=p;imageIndex=0;$('dialogCollection').textContent=p.collection||'NULL//LUX';$('dialogName').textContent=p.name;$('dialogPrice').textContent=money(p);$('dialogDescription').textContent=p.description||'';$('dialogTags').replaceChildren(...(p.tags||[]).map(t=>{const s=document.createElement('span');s.textContent=t;return s}));const link=$('buyButton');if(/^https:\/\//.test(p.purchaseUrl||'')){link.href=p.purchaseUrl;link.classList.remove('disabled');link.textContent='VIEW PRODUCT ↗';$('purchaseNote').textContent='Complete your order on the linked product page.'}else{link.removeAttribute('href');link.classList.add('disabled');link.textContent='COMING SOON';$('purchaseNote').textContent='This design is being prepared for release.'}renderGallery();$('productDialog').showModal()}
function renderGallery(){if(!activeProduct)return;const imgs=activeProduct.images||[];imageIndex=(imageIndex+imgs.length)%imgs.length;$('dialogImage').src=safeImage(imgs[imageIndex]);$('dialogImage').alt=`${activeProduct.name} mockup ${imageIndex+1} of ${imgs.length}`;$('galleryCounter').textContent=`${String(imageIndex+1).padStart(2,'0')} / ${String(imgs.length).padStart(2,'0')}`;$('thumbnails').replaceChildren(...imgs.map((src,i)=>{const b=document.createElement('button');b.type='button';b.className=i===imageIndex?'active':'';b.setAttribute('aria-label',`Show mockup ${i+1}`);const img=document.createElement('img');img.src=safeImage(src);img.alt='';b.append(img);b.onclick=()=>{imageIndex=i;renderGallery()};return b}));$('prevImage').hidden=$('nextImage').hidden=imgs.length<2}
$('search').addEventListener('input',()=>catalog&&renderProducts());$('prevHero').onclick=()=>moveHero(-1);$('nextHero').onclick=()=>moveHero(1);$('prevImage').onclick=()=>{imageIndex--;renderGallery()};$('nextImage').onclick=()=>{imageIndex++;renderGallery()};$('closeDialog').onclick=()=>$('productDialog').close();$('productDialog').onclick=e=>{if(e.target===$('productDialog'))$('productDialog').close()};$('menuButton').onclick=()=>{const open=document.querySelector('nav').classList.toggle('open');$('menuButton').setAttribute('aria-expanded',String(open))};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.querySelector('nav').classList.remove('open'));init();
