const $=id=>document.getElementById(id);let catalog={schemaVersion:1,settings:{carouselStyle:'slide',carouselSeconds:5},products:[]},workingImages=[],db;
function notify(message){$('status').textContent=message}
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open('null-lux-threads-studio',1);request.onupgradeneeded=()=>request.result.createObjectStore('drafts');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function getDraft(){return new Promise((resolve,reject)=>{const t=db.transaction('drafts','readonly');const r=t.objectStore('drafts').get('catalog');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function saveDraft(){return new Promise((resolve,reject)=>{const t=db.transaction('drafts','readwrite');t.objectStore('drafts').put(catalog,'catalog');t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
const safeImage=s=>typeof s==='string'&&(s.startsWith('data:image/')||/^https?:\/\//.test(s)||/^assets\/[a-zA-Z0-9._/-]+$/.test(s))?s:'';
function renderList(){const list=$('studioList');list.replaceChildren(...catalog.products.map(p=>{const li=document.createElement('li'),name=document.createElement('span'),btn=document.createElement('button');name.textContent=`${p.name} · ${(p.images||[]).length} mockups${p.published===false?' · hidden':''}`;btn.textContent='EDIT';btn.onclick=()=>edit(p.id);li.append(name,btn);return li}));$('studioCount').textContent=String(catalog.products.length).padStart(2,'0')}
function renderImages(){const preview=$('assetPreview');preview.replaceChildren(...workingImages.map((src,i)=>{const box=document.createElement('div'),img=document.createElement('img'),remove=document.createElement('button');img.src=safeImage(src);img.alt=`Mockup ${i+1}`;remove.textContent='×';remove.type='button';remove.setAttribute('aria-label',`Remove mockup ${i+1}`);remove.onclick=()=>{workingImages.splice(i,1);renderImages()};box.append(img,remove);return box}));notify(`${workingImages.length} mockup${workingImages.length===1?'':'s'} attached to this product.`)}
function resetForm(){$('productForm').reset();$('productId').value='';$('isNew').checked=$('featured').checked=$('published').checked=true;$('deleteProduct').hidden=true;workingImages=[];renderImages()}
function edit(id){const p=catalog.products.find(x=>x.id===id);if(!p)return;$('productId').value=p.id;for(const k of ['name','collection','description','price','purchaseUrl','printifyProductId'])$(k).value=p[k]??'';$('tags').value=(p.tags||[]).join(', ');for(const k of ['isNew','featured','published'])$(k).checked=p[k]!==false;workingImages=[...(p.images||[])];$('deleteProduct').hidden=false;renderImages();$('productForm').scrollIntoView({behavior:'smooth'})}
const readImage=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file)});
$('images').onchange=async event=>{const files=[...event.target.files];for(const f of files){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>8*1024*1024){notify(`Skipped ${f.name}: use PNG, JPEG or WebP under 8 MB.`);continue}workingImages.push(await readImage(f))}event.target.value='';renderImages()};
$('productForm').onsubmit=async event=>{event.preventDefault();if(!workingImages.length){notify('Add at least one mockup before saving.');return}const id=$('productId').value||crypto.randomUUID(),existing=catalog.products.find(p=>p.id===id);const url=$('purchaseUrl').value.trim();if(url&&!url.startsWith('https://')){notify('Purchase URL must start with https://');return}const p={id,name:$('name').value.trim(),collection:$('collection').value.trim(),description:$('description').value.trim(),price:Number($('price').value),currency:'USD',tags:[...new Set($('tags').value.split(',').map(t=>t.trim()).filter(Boolean))],isNew:$('isNew').checked,featured:$('featured').checked,published:$('published').checked,createdAt:existing?.createdAt||new Date().toISOString(),images:[...workingImages],printifyProductId:$('printifyProductId').value.trim(),purchaseUrl:url};if(!p.name||!Number.isFinite(p.price)||p.price<0){notify('Enter a name and valid price.');return}if(existing)Object.assign(existing,p);else catalog.products.unshift(p);try{await saveDraft();renderList();resetForm();notify('Saved in this browser. Export catalog.json to publish.') }catch(e){notify('Could not store draft. Compress images and export a backup.');console.error(e)}};
$('clearForm').onclick=resetForm;$('deleteProduct').onclick=async()=>{const id=$('productId').value;if(!id||!confirm('Delete this product from the draft catalog?'))return;catalog.products=catalog.products.filter(p=>p.id!==id);await saveDraft();resetForm();renderList();notify('Deleted from draft. Export to publish the change.')};
$('saveSettings').onclick=async()=>{catalog.settings={carouselStyle:$('carouselStyle').value==='fade'?'fade':'slide',carouselSeconds:Math.max(2,Math.min(20,Number($('carouselSeconds').value)||5))};await saveDraft();notify('Carousel settings saved. Export to publish.')};
$('exportCatalog').onclick=()=>{const content=JSON.stringify(catalog,null,2),blob=new Blob([content],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify(`Exported ${catalog.products.length} products. Commit catalog.json at your repository root.`)};
$('importCatalog').onchange=async event=>{const f=event.target.files[0];if(!f)return;try{const incoming=JSON.parse(await f.text());if(incoming.schemaVersion!==1||!Array.isArray(incoming.products)||!incoming.settings)throw Error('Unrecognized schema');if(!confirm('Replace local drafts with this catalog?'))return;catalog=incoming;await saveDraft();renderList();resetForm();$('carouselStyle').value=catalog.settings.carouselStyle==='fade'?'fade':'slide';$('carouselSeconds').value=catalog.settings.carouselSeconds||5;notify('Catalog imported into this browser.')}catch(e){notify('Import failed: invalid catalog or insufficient browser storage.');console.error(e)}event.target.value=''};
(async()=>{try{db=await openDb();const saved=await getDraft();if(saved)catalog=saved;else{const response=await fetch('catalog.json',{cache:'no-store'});if(!response.ok)throw Error('Catalog unavailable');catalog=await response.json();await saveDraft()}renderList();$('carouselStyle').value=catalog.settings?.carouselStyle==='fade'?'fade':'slide';$('carouselSeconds').value=catalog.settings?.carouselSeconds||5;resetForm()}catch(e){notify('Studio unavailable. Open this site on a modern browser and refresh.');console.error(e)}})();
